### ISSUE TITLE
🛠️ [TASK] : Cleanup API endpoints

### ISSUE THREAD

**Issue by bkioshn** [input-output-hk/catalyst-voices#1029]
### Summary

Cleanup API endpoints

### Description

Cleanup the existing endpoint in `catalyst-gateway`

### Subtasks
- [x] Change the existing endpoints to `draft`
    - All API should be `/api/draft/*` except for `health` and existing versioned endpoint. 
    - `/api/v1/health` `v1` can be assign to `health` endpoint since it is stable
- [x]  Remove `BadRequest` from [ErrorResponse](https://github.com/input-output-hk/catalyst-voices/blob/a330c53efca17fb52c872e104e2da833c4102ea1/catalyst-gateway/bin/src/service/common/responses/mod.rs#L26)
    - Bad Request 400 should be custom to a certain endpoint
    - Check the existing endpoint that may return 400 and assign appropriate BadRequest error
- [x] config endpoint should get json schema from OpenAPI specification
- [x] Add openapi linting rule in `.spectral`
    - Checking the api path
    - Checking that the content type shouldn't be `text/plain`
    - All properties and schema should contains example
    - If content type is `application/json` it should be object
- [x] Revisit document
- [x] Restructure legacy endpoints
    - All legacy endpoints should be under Legacy tag
- [x] Add API key auth
- [x] Properly handle response (401, 403, 422, 429, 500, 503
- [x] Handle headers (retry after, ratelimit, access control allow origin
