### ISSUE TITLE
🏛️ [EPIC] : Catalyst Gateway PostgreSQL Schema

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#1034]
### Summary

Build the Schema for Catalyst Gateway

### JIRA Epic

TODO

### Description

Flesh out the schema for catalyst gateway.

As much of the data within Catalyst will be polymorphic, with different options or parameters at each level of the schema, we should employ JSONB columns to effectively capture this polymorphic data without creating overly complex schemas.

Also consider that this data will ultimately need to be decentralized in one for or another, so do not use natural identifiers (such as sequential record id's).  Instead, use things like UUID.  Keep this aspect in mind when designing the DB to help ease a transition to a decentralized version of the data.

### Configuration

- [x] Add Configuration tables.
  - [x] Add Business logic to read/write configuration tables.

### Initial Setup

- [x] Add initial base tables and their relationships, but little to no data.

### Brand

- [ ] Gather data requirements for the Brand tables.
  - [ ] Document them in the Architecture documentation for cat-voices.
- [ ] Enhance the Brand schema to properly capture that data.

### Campaign

- [ ] Gather data requirements for the Campaign tables
  - [ ] Document them in the Architecture documentation for cat-voices.
- [ ] Enhance the Campaign schema to properly capture that data.

### Event

- [ ] Gather data requirements for the Event tables
  - [ ] Document them in the Architecture documentation for cat-voices.
- [ ] Enhance the Event schema to properly capture that data.

### Category

- [ ] Gather data requirements for the Category tables
  - [ ] Document them in the Architecture documentation for cat-voices.
- [ ] Enhance the Event schema to properly capture that data.

### Proposal

- [ ] Gather data requirements for the Proposal tables
  - [ ] Document them in the Architecture documentation for cat-voices.
- [ ] Enhance the Proposal schema to properly capture that data.
