### ISSUE TITLE
🏛️ [EPIC] : Platform & General Interface

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#105]
### Summary

The basic application framework and consistent interface patterns across the experience.

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

The Catalyst Voices platform will be delivered as a Flutter application, written using Dart and Material3. The MVP will be a responsive web app that is optimized for desktop, with limited functionality on mobile. Wallet connect (and therefore most features) will be available only on desktop browser. Future iterations of the platform will include native applications for iOS and Android, dependent on development of new SDKs to enable wallet connect and other key features on mobile. 

Users will enter the MVP webapp from a variety of sources, including but not limited to...

- Direct URL (likely subdomain of ProjectCatalyst.io)
- ProjectCatalyst.io ("Launch App)
- Contextual Deep Linking

Across the Voices platform, a consistent general interface will allow users to navigate the experience with context and confidence, even as they take on new roles & actions, or interact with new brands & spaces. Pieces will include:

- Header: logo, main call to action, inventory, account / profile
- Left Rail: expandable hamburger menu with navigation that changes based on application context
- Right Rail: expandable panel with just in time tips to complete actions with ease & quality based on application context
- Footer: static key links

The interface will not only be responsive to application context, but also to user context. Users may see different information or actions available in the general interface based on...

- Account connected state
- Registered / active roles
- User preferences

A note on existing website vs Voices: 

Some overlap may exist between these two interfaces for the MVP of Voices, including the ability to browse events and proposals. Over time, it is anticipated that features currently in the website - like the ability to explore funded project progress & results - will be incorporated into the Voices platform post-MVP. In a mature state, it is envisioned that the website will hold high-level descriptive information relevant to Catalyst as a process and as a service, while all user-driven interactions will live inside the platform. Open question: how is existing website built, and is there compatibility with how app will be built?

TODO: consider desirability & feasibility for MVP of super admin user interface for allowing non technical platform operators to perform management functions like template editing, moderation, etc.

TODO: define how UX components will be reusable across brands. Need to implement components in such a way that they can pull in logo and other assets from either Catalyst, or any other user / customer. Might consider achieving this using ThemeData from flutter: https://api.flutter.dev/flutter/material/ThemeData-class.html

### Todo

- [x] #379 
- [x] #380 
- [x] #381 
- [x] #382 
- [ ] Application architecture & setup
- [ ] New user onboarding flow
- [x] [TASK] Develop proposal workspace navigation drawer component
- [x] #469

**Comment by minikin** [comment]
@mike-mcnulty "Contextual Deep Linking" has nothing to do with the initial implementation of UIKit. Can we de: scope it, please?

**Comment by mike-mcnulty** [comment]
TODO: split deep linking into its own epic

**Comment by mike-mcnulty** [comment]
completed with mve1
