### ISSUE TITLE
🏛️ [EPIC] : Login (Connect Account)

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#106]
### Summary

Users will need to login to access the Voices experience

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

Catalyst Voices users will have several ways to access the platform. The primary way will be to connect a Cardano wallet using the CIP30 wallet connector. Users with an existing account will also be able to login using a seed phrase or QR code generated at account creation. More details on this secondary method are included in the "Catalyst Seed Phrase" section below. 

First time users without an existing Cardano wallet will still have the option to create a basic Catalyst account, with the option to associate a Cardano wallet later. This offers a gentle onboarding experience to users that may be unfamiliar with web3, while introducing foundational concepts like seed phrases and self-custody. Users with this basic account will not be able to create proposals, cast votes, or earn rewards -  giving them an incentive to complete wallet creation, connection, & role registration.

Multiple Cardano wallets may be associated to the same Catalyst account, enabling users to consolidate voting power across wallets, without requiring workarounds like self-delegation. 

### Mobile Users

Direct wallet connect will not be available to mobile users, until we deliver native iOS & Android apps in future iterations of the platform. We explore potential intermediate approaches and their tradeoffs [here](https://input-output.atlassian.net/wiki/spaces/VIT/pages/4106289246/Support+for+mobile+browser+wallet+connect). 

Mobile users will have the ability to access full functionality, given they are able to get one-time access to a desktop computer for initial account creation, setup, and role registration. 

### CIP Overview

- CIP15/36 - Support for old Catalyst registration methods (pending further discussion on feasibility / desirability of investing in backward compatibility - not covered in scope of proposal grant)
- CIP30 - Connect browser extension wallet to app
- TBD - New CIP that improves Catalyst registration format with support for new roles and role based access control
- CIP95 - Ability to prove ownership of Cardano drep registration (out of scope for MVP)
- 751/752/753 - Draft CIPs for new RBAC

### Catalyst Seed Phrase

https://docs.google.com/presentation/d/1Oxj7KW6IS4971IENQ0EFCV1sQ9VCsVdLhkZzVDbvDDY/edit#slide=id.p1

Exploring a novel approach that leverages recent work in the core node team, related to 1694. It would give users the ability to create a new private/public key pair that can be managed by the application (rather than the wallet). This will give us more direct control over the UX when it comes to signing data & user actions. It will be compatible with CIP30, and will work without any new development effort from ecosystem wallets.

Practically, this will mean we need browser-extension wallet interaction at with user input for spending password at the point of
-Wallet Connect
-Role Registration

We will have full control over all other parts of the process, including proposal submission & vote casting. Depending on user needs, we may implement confirmations or even a pin similar to the current UX, but there will be no hard requirements imposed by the technical approach, as previously assumed.

Another benefit unlocked by this approach is a straightforward way to associate multiple stake keys to a single Catalyst account, offering self-delegation and consolidation of wallets for a single user - that is distinct from drep registration.

This could also give us a method to offer high quality, full experience to mobile users, even in the MVP (prior to delivery of a native mobile app). After one time creation of account / role registrations on a desktop, a user could use the Catalyst seed phrase to login to the experience, even on a mobile browser.

Benefits of key recovery:
- Rolling keys allow users to create new catalyst keys, associated to their stake address, so that they do not lose past contributions
- Can re-register even in the middle of voting, without disruption or loss of previously submitted votes

Temporary account:
This approach opens the potential to give users a basic account that does not require any Cardano wallet to get started. Users may create Catalyst key, use it as login, and have ability to take basic functions like create profile, save favorites.

This temporary account and everything associated with it can be later associated to a Cardano stake address, to open new abilities, without losing the profile / preference information already accumulated. 

### Role Registration 

Upon account creation, users will be immediately launched into the Role Registration workflow. They will be able to view all roles, understand their details, and submit role registrations to mainnet. First time users will be required to opt-in / opt-out of all roles, so that they can better understand the different ways to engage as they get started. 

This step may be abandoned at any time, and can only be completed by users with a connected wallet. Users that have created an account without a connected wallet should be nudged into a Create Wallet workflow when they attempt to proceed with this step. 

Users may revisit role registration at any time. They may enter the workflow in two ways:
1) manually navigate to profile > role mgmt > select role and go through registration wizard
2) attempt to take priveliged action for role you do not have, launch the registration wizard for that related role

### Account Creation = Voter Registration

When a user creates their Catalyst Account, they will implicitly be registering as a voter. When a wallet is connected to the account and signs a transaction to claim / associate the account with the wallet on chain, a new voter registration should also be created.

If a user does not sign a transaction with their wallet during account creation, they will receive notifications / tasks encouraging them to "complete account creation / setup". Until they do so, they will have a "lite" account with minimal functionality. 

Once account creation is completed, the user will become a full "Citizen" with the ability to 
-Vote
-Comment
-Unlock other role registrations

###User Feedback

[User test1 ](https://docs.google.com/document/d/1KZdF3e_hKZs_9ddGGgjmhS8kC5aEr55ckxjIvqWIMJ8/edit)(closed doc)

### Todo

Login 

- [x] #334 
- [x] #335 
- [x] #336 
- [x] #337 
- [x] #338 
- [x] #355 

Help

- [ ] Learn More
- [ ] Create Wallet
- [ ] Supported Wallets

Role Registrations

- [ ] Role Overview
- [ ] Role Details
- [ ] Register as Voter
- [ ] Register as Drep
- [ ] Register as Proposer

**Comment by mike-mcnulty** [comment]
refined MVP scope completed in mve2
