### ISSUE TITLE
🏛️ [EPIC] : My Account

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#107]
### Summary

Users can manage roles, preferences, and more inside their account

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

Catalyst users will require an account to access the majority of the platform experience, including registering for roles, creating proposals, and casting votes. 

A single Catalyst account may be associated to one or more Cardano wallets, and may have 1 or more attached role registrations.

When users view their account inside the application, they will be able to find key information about their profile, wallet, roles, rewards, and participation history. Users may also manage tasks from inside their account. 

Profile gives users a shareable location to share discoverable information with other users on the platform. It may contain a mix of private and public information, where private is viewable only to the user to create a personalized experience, where public is viewable to anyone. 

Wallet information should give users confidence that they have connected the correct wallet. Users should be able to see their wallet address, staking key, current ada holdings, and a timestamp of when wallet data was last refreshed. If a user has connected multiple wallets, they should be able to see the same across all wallets, with a consolidated rollup that shows total ada across connected wallets.

Role overview should show users which roles they currently have, and offer a path to creating new role registrations. Users should be able to understand the abilities and opportunities associated with each role. 

Rewards should show users the total earned vs paid rewards across all roles and events. There should be a way to easily segment rewards by event (eg Fund12) or role (eg Voter rewards).

Participation history will give users an easy way to view their recent activity in the app. Entries may include proposal updates, recent comments, tasks completed, or rewards earned.

Tasks management will help users understand what actions need to be taken (and by when), so that they can participate in a given event. Users need to be able to easily see which active / upcoming events they are eligible / registered to participate in. Task management should help guide & prioritize user actions in the app. A task should be defined by Role, Action, Deadline, Reminders, & Message.

### Todo

Account Info

- [ ] Nickname
- [ ] Avatar
- [ ] Discuss private account vs public profile; privacy by design approach; might want to store some info locally that offers nice personalized experience, but don't want that stored in public db or viewable on my public profile
- [ ] Discuss relevant wallet info to capture / display, consider: ID, address, HEX identifier thingy; ability to copy quickly copy receive address so platform becomes enabler for p2p tx, even prior to offering p2p tx in platform
- [ ] Set privacy settings on all pieces of account info
- [ ] Public bio / personal statement (belong in separate profile section, distinct from account mgmt?

Profile Icon Dropdown 
https://www.figma.com/file/1e1MMDXyi0oL9sG9IunWL7/UI-Kit-Figma-for-catalyst?type=design&node-id=1090-14843&mode=design&t=BV2PAMkXxfLnqDo2-0

Activity
- [ ] Browse recently completed actions including registrations, proposal creation / edits, votes
- [ ] Get notifications about relevant activity completed by others, eg collaborator proposal edits, comments

Task Manager
- [ ] Serve priority tasks to users based on active roles, followed events, and recent activity
- [ ] Reminders about upcoming deadlines like voter registration and proposal submission
- [ ] Task & opportunity discovery to earn rewards, gain experience, get reputation
*Note: task mgmt will take a constrained approach in the MVP. Specific approach to be discussed and agreed. May make use of Notifications, Timeline, or a simplified Inventory
- [ ] Task Lister UI Component #281  

Inventory
- [ ] List view of all my ideas, with ability to search, sort, filter based on status & themes
- [ ] Shareable public inventory page that can easily be shared; personal landing page for my ideas

Manage Roles

- [ ] See current roles, including title, registration timestamp / epoch
- [ ] See available roles
- [ ] Initiate registration for available roles
- [ ] See locked roles
- [ ] Batch Submit UI Component #278  

#211 

Understand Roles

- [ ] Description
- [ ] Privilege Actions
- [ ] Rewards Opportunities

View Rewards

- [ ] View total rewards
- [ ] View rewards by role
- [ ] View earned vs paid rewards

*Current rewards schemes are described in the gitbook parameters document: https://docs.projectcatalyst.io/current-fund-basics/fund11-parameters

Manage Preferences
- [ ] Determine relevant preferences for MVP
- [ ] Determine 'privacy by design' approach with engineering
