### ISSUE TITLE
🏛️ [EPIC] : MVE5: Setup & Browse Final Proposals

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#1072]
### Summary

MVE5

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

Intent: By giving proposers the ability to publish their proposals into the voting space, we allow them to signal that a proposal is ready for consideration. We let voters use lists to bookmark proposals, so they can narrow their focus for review and decision making.  

Description: Let proposers publish final proposals to the voting space, and let voters browse those proposals in the voting space, with ability to bookmark proposals in lists

Outcome: Get proposer feedback on proposal publishing experience, and validate that drafts vs final proposals is understandable; get the same for community members, discover needs for organizing proposals prior to casting votes

Focus roles: proposer + voter

Value Delivery
-Enable proposers to submit their ideas for community decision
-Accelerate ecosystem innovation with crowdsourced ideas
-Enable us to get feedback on publishing and bookmarking experience

Design Principles
-Reduce overwhelm
-Enrich data over time
-People powered innovation

Expected experiment outcome: We want proposers to tell us that the proposal lifecycle is simple to understand and navigate. We want voters to tell us how we might make it easier to manage proposal volume for review and decision making

Workflow:
-ADMIN <double check everything related to categories rules and validations, proposal eligibility, etc.>
-PROPOSER view drafts, select for publishing, complete pre flight check, sign with key
-VOTER view campaigns, categories, proposals, comments and REVIEWs in voting space #discuss: compatibility with reviews process planned for repurposed moderation module

**Consider: continuous innovation. Has this proposal been submitted before? Useful data point for making decision. Bell curve of confidence with more rounds Could be relevant angle to bring in the versioning stuff across other spaces too. 

Action Labels
-Publish individual proposal to voting space
-View proposal detail
-View proposal version history
-Save / restore proposal version history

**Consider where version history fits in. Could be good place here, though deviates from rest of frame. This one may turn out to be quite light, since publishing to voting space will closely mirror share to discovery space. We already have favorites in place, and will just be a bit of thinking on how to extend for voting, if at all. Could also just split into 2 small MVEs. Basically need PROPOSER view / restore history, and add that somewhere to VOTER’s proposal detail view**

Extract addtl requirements from #111 

### Design Tasks

- [ ] #1211 
- [ ] #1212 
- [ ] Define proposal editing experience, including component behavior (tix exist already?)
- [ ] Proposer view incomplete questions / tasks (bundle with pre flight check?)
- [ ] #1213 
- [ ] Proposer add / change category (tix already exist?)
- [ ] #1214 
- [ ] Proposer publish final proposal to voting space (and removes from DS)
- [ ] Proposer retract final proposal from voting space
- [ ] Voter view final proposal listers (will be part of MVE4?)
- [ ] Voter view final proposal details modal (will be part of MVE4?)
- [ ] #1216 
//Consider whether comments in scope for this MVE, given resequencing. Won't have comments until future MVE, since we pushed discovery space / commenting for later.
- [ ] #1217 
- [ ] #1215 
- [ ] Scout ahead: add proposals to voting list, including "copy favorites"
- [ ] Scout ahead: review, confirm, sign, and submit votes

### Architecture Tasks
- [ ] Define anything outstanding related to voter role registration / key derivation. Build foundations for voter-role RBAC in next MVE.

### Backend tasks:
- [ ] GIVEN proposer role key POST final proposal
- [ ] GIVEN proposer AND proposal UPDATE proposal status (private > draft > published)
- [ ] IF proposal published THEN read only, even for proposal owner
- [ ] GIVEN proposal GET proposal details
- [ ] GIVEN proposal GET proposal history
- [ ] #233 
- [ ] GIVEN proposal GET view count AND sort default list by view count desc
- [ ] Submit rollup of registrations & final proposals to chain [discuss]
