### ISSUE TITLE
🏛️ [EPIC] : Content (Discovery Space)

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#108]
### Summary

Define types of content and how users navigate them

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

Content includes events, categories/challenges, ideas/proposals, and comments. 

All users can view content. How users are able to interact with content is determined by roles / ownership.

If users attempt to perform an interaction that they do not have sufficient privileges to complete, they will be prompted to register for the required role. Upon successful registration, the user should be brought back to the point of interaction so that they can complete the desired action.

TODO: explore feasibility and desirability for MVP to include concepts such as For You, personalized feed of information vs default view. Consider examples like Twitter, Reddit for content discovery and navigation (trending, newest, most commented, most votes, hottest, viewing content within an event context vs across events / spaces). Need to understand how we might balance personalization and stored preferences with privacy by design, leveraging ideas like local caching and encrypted data storage. Offer ways to personalize the experience with toggles, filters, etc that can persist over time.

Consider: how might users want to navigate information in the most impactful way, with the fewest clicks. Discover favorites, participate in hot discussions, support proposals they love
-Tabs / pills / toggles for quickly moving between types like draft vs proposal
-Same for seeking funding vs funded vs completed
-Other 'quick filters' we might explore like latest, most voted, etc.

Sort / Filter:
-By Category
-By Fund / Event
-By theme (eg DAOs, dApps, Data, etc - see Ideascale Tags)
-Budget Requested
-Open Source
(once available >)
-Review Score
-Votes Cast 
-Already Voted / Not Voted Yet

### Todo

Access Control & Visibility

- [ ] Define what lurkers (no account / no roles) can see
- [ ] Define what voters / commenters can see
- [ ] Define what proposal owners can see
- [ ] Define what proposal collaborators can see

Events

- [ ] Browse events: default presentation
- [ ] Find events: search, sort, filter
- [ ] Discover events: preference and participation history driven, personalized recommendations
- [ ] View event details
- [ ] Share links

Categories / Challenges

- [ ] Browse categories: default presentation
- [ ] Find categories: search, sort, filter
- [ ] Discover categories: preference and participation history driven, personalized recommendations
- [ ] View category details
- [ ] Share links

Ideas / Proposals

- [ ] Browse ideas: default presentation
- [ ] Find ideas: search, sort, filter
- [ ] Discover ideas: preference and participation history driven, personalized recommendations
- [ ] View idea details
- [ ] Share links

Comments

- [ ] Browse events: order chronologically by default
- [ ] Expand / collapse nested comments
- [ ] Find events: search, sort, filter
- [ ] Discover events: preference and participation history driven, personalized recommendations
- [ ] View comment details
- [ ] Share links

Linked Stories
- [x] #313

**Comment by mike-mcnulty** [comment]
TODO: split into each type of content, for each:
Overview + detail view
