### ISSUE TITLE
🏛️ [EPIC] : Grants Space / Funding Track / Vote

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#109]
### Summary

Register and take action as a voter

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

All users, including those without a connected account will be able to browse events, view funding track details, and discover new proposals. Only those with a Voter role registration will be able to save favorites, make voting selections, and cast votes to participate in funding allocation. 

Users will have several options for discovering proposals. They may navigate via categories, filter for particular themes, or manually search / sort. Users will be able to view many proposals in a list, with only key pieces of metadata visible. They will have the option to click into each proposal to view all details. Each detailed page will have a link for easy sharing. A user may click on the avatar of the proposer on a proposal, in order to view their proposer profile, where they may explore other active and previous proposals by the same user. 

Users will be able to view the fund timeline at a glance, with the ability to view details on particular actions, deadlines, and ways to participate at each stage. Users will be able to subscribe to an event to receive notifications about each stage. Users may opt to subscribe to notifications from the event overview, and if they take action within an event such as saving a favorite or casting at least 1 vote, they should be nudged to turn on notifications so they don't miss important times like the end of the event. 

Before voting opens for an event, primary user actions will be proposal-level comments, saving favorites, and sharing proposals. Users will be able to streamline the vote cast experience once voting opens, by using their favorites list to help focus their decision making attention. Key pieces of meta data that will be useful to users at this point when browsing proposals to include number of comments and number favorites.

Once voting opens, users will primarily focused on casting votes. Key pieces of meta data that will be useful to users at this point will be current number of votes cast and the current voting stake.

Once voting closes, users will be able to easily browse overall voting results, as well as see results at a glance for proposals that they voted on. They will be able to see their own vote selection alongside the final voting results. Key pieces of meta data that will be useful to users at this point will be total number of votes cast, total voting stake, and the count / stake across all voting options. 

Aspirational future use cases for voting on Voices (demonstrative)
- CIP approval
- 1694 governance action temperature checks
- Dreps poll delegators
- SPOs poll delegators
- Community treasury allocation beyond Catalyst

Consider: how might "challenge-minded" voting help promote better decision outcomes, and help each voter make the most of their voting power? Suppose UI that prioritizes mindful allocation of entire fund budget, rather than emphasizing picking individual winners. Full UX postMVP. Explore opportunities to educate users and avoid "cannibalizing" own votes by over allocating budget in the MVP. Useful data point in context: total challenge budget allocated vs total budget available. Further discussion about value of enforcing challenge-focused voting. UI-side validation is possible in MVP, but system-level validation that still maintains privacy dependent on future cryptography research.

TODO: voting & delegation for "un-registered voters" ie voters that meet voting requirements, but have not submitted a registration to mainnet

###Misc.

As a user, I need to understand the point of submitting an abstain vote, so that I will cast those types of votes.

As a user, I need the ability to choose whether to continue voting OR submit votes now. It should be seamless to take either action, after every proposal selection I make during voting. 

As a user, I want to maximize my voting power based on my holdings, so that I can have as much influence as possible. In a perfect world, I can vote using stake that is locked in defi or in my unclaimed staking rewards. I might be interested in performing value add activities for the ecosystem, in return for temporary / decaying boost in decision influence. 

### Todo

- [ ] Event Overview
- [ ] Event Detail
- [ ] Event Timeline
- [ ] Follow Event
- [ ] Proposal List
- [x] #234 
- [ ] Proposal Detail
- [ ] Proposal Summary (user or AI?)
- [ ] Proposer Profile
- [ ] Favorite Proposal
- [ ] Favorites List
- [ ] Decision Select
- [ ] Vote Sign & Submit
- [ ] Batch Submit UI Component #278  
- [ ] Voting History, including Voting Results & Rewards
- [ ] Voting Results, RealTime and Final

Direct Voter

- [ ] Register as a voter
- [ ] See voting power

Representative Voter

- [ ] Register as a drep (must be a registered voter to unlock this role)
- [ ] Provide optional profile information

- Name | String
- Contact | String
- Voted previously? | Checkbox
- Also Cardano Drep? | Checkbox (future state: validate CIP95 registration attached to wallet)
- Motivation | String - 2500 char limit
- Expertise / skills / domain expertise / themes | Multi Select Tags
- Agree to duties | Checkbox

SRC: https://docs.google.com/forms/d/1PNHa7_98z9cym-xc65AlRNtiuk4Q5sCE1GPHkkYI4m8/viewform?edit_requested=true

- [ ] See personal and total delegated voting power

- My Staked ADA | Integer
- Number of Delegations | Integer
- Total Delegated ADA | Integer
- Saturation | Percentage

REF on saturation: 
https://input-output.atlassian.net/browse/NPG-1369
https://input-output.atlassian.net/browse/NPG-2125

Voter Actions

- [ ] Select proposals
- [ ] Submit votes
- [ ] View voting history
- [ ] View voting rewards
- [ ] As a voter, I need to know the total challenge budget vs total budget allocated by vote, so that I know how much budget I have left to spend in a challenge, and I can avoid cannibalizing my own vote by over-voting. 
-
