### ISSUE TITLE
🏛️ [EPIC] : Delegate

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#110]
### Summary

Passive participation in decision making

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

Delegation is for those that want to participate and earn rewards, but want to do so passively and with minimal effort.

Delegators give voting power to selected representatives, but maintain control over own ADA holdings.

### Todo

Delegate

- [ ] Browse dreps

List view that includes subset of drep profile info, with ability to search, sort, filter dreps
-Name
-Tags
-Character limit on motivation statement (60char?)

Ref: https://app.testnet.projectcatalyst.io/delegations

- [ ] View drep details

Detailed page with all drep info
See drep voter registration info: https://github.com/input-output-hk/catalyst-voices/issues/109
Ref: https://app.testnet.projectcatalyst.io/drep/ntesovic00

- [ ] Select dreps
- [ ] Submit delegation
- [ ] Remove delegation
- [ ] Drep Registration Timeline
- [ ] Delegation Timeline
- [ ] View delegations
- [ ] View delegated voting history
- [ ] View delegation rewards

### Background

An initial drep onboarding flow was created and communicated as part of the now sunset "Governance Voting Center". Although we want to iterate on that process (for example, not managing a central database of personal info), we should leverage that prior thinking as a starting point. 

UX: [Figma ](https://www.figma.com/file/DwsPg7NGx136GPheJlp1DX/UI-(V1)---Governance-Voting-Centre-Dapp?type=design&node-id=2746-116636&mode=design&t=TmJcgDxg6prLNVZv-0)flow [OLD] and live [app ](https://app.testnet.projectcatalyst.io/)deployed to testnet

Waitlist: Google [form ](https://docs.google.com/forms/d/1PNHa7_98z9cym-xc65AlRNtiuk4Q5sCE1GPHkkYI4m8/viewform?edit_requested=true)with responses from drep hopefuls

Community Workshops: Slides for [first ](https://docs.google.com/presentation/d/1jg6XyoRW8akg1HGR-KaxEcSMHZE1-tu4DT-YTQUH5zs/edit#slide=id.gdfa3e222b6_0_351)and second [workshop](https://docs.google.com/presentation/d/1WHBXfDL6XXWj5cL3WXLOK6J7MsokOKsMsZDuTVYRMiU/edit#slide=id.g14ff9f69c4c_0_90)

**Comment by mike-mcnulty** [comment]
TODO: think about funding track timeline, nudging people into action, thinking about tasks
