### ISSUE TITLE
MVE 3 + MVE Delivery checklist

### ISSUE THREAD

**Issue by nielskijf** [input-output-hk/catalyst-voices#1119]
## MVE Delivery:
- [ ] Design consolidated in MVE3 RC
- [ ] Remove what is not applicable for MVE
- [ ] Cards/Components under designs
- [ ] Flow in protoype (Shift-E in figma to see noodles)
- [ ] New components overview
- [ ] Bring in Ticket format
