### ISSUE TITLE
🏛️ [EPIC] : Collaborate

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#112]
### Summary

Proposers can choose to submit proposals as part of a team

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

Teams of proposers are called collaborators. Collaborators edit ideas together, and must agree to make final submissions.

### Todo

Collaborate

- [ ] Register as co-proposer
- [ ] Request to collaborate
- [ ] Invite to collaborate
- [ ] Approve collaboration
- [ ] Initiate proposal finalization
- [ ] Approve proposal finalization

Idea Editing

- [ ] Define collaborative doc editing UX
