### ISSUE TITLE
🛠️ [TASK] : Implement discovery homepage UI

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#1195]
### Summary

Implement discovery homepage UI

### Summary

Discovery homepage for Actors | unlocked

**Empty State**
As a user I want a clear indicatoin when proposals are not yet available (empty state), so I know there is nothing to do yet.

**Filled State**
As a user I want to see the page populated with draft proposal listers, so I know I can start engaging with proposers.

### Description

- [x] Discovery Space : homepage | empty state #1182 
- [x] Discovery Space : homepage | filled state
- [ ] CTA: Discover Campaign Details #1171
- [ ] Campaign Details modal #1171

Figma design: [Homepage (empty/filled), Campaign Details modal](https://www.figma.com/design/80aDAQgoD0v06DO2Sb76ok/Catalyst--Minimal-Valuable-Experiments-(MVE's)?node-id=7860-111722&t=UkYra33FEDsXFBXw-4)

Relates to: #1068

**Comment by dtscalac** [comment]
@mike-mcnulty how should it look if non registered or a user with locked keychain goes there?

**Comment by dtscalac** [comment]
> @mike-mcnulty how should it look if non registered or a user with locked keychain goes there?

@nielskijf question for you too 👍

**Comment by nielskijf** [comment]
A copy of the states discovery page [here](https://voices.projectcatalyst.io/m4/discovery) with the correct selection / text only is enough for the designs not provided, we will detail these soon.
page - visitor/nokey - text: page - visitor/nokey
page - unlocked (provided design) - Key found (Actor/unlocked)
page - key/locked - text: Key found (Guest/locked)
