### ISSUE TITLE
🛠️ [TASK] : Integration test data setup for voting

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#122]
### Summary

Setup test data for integration tests for voting

### Description

Create a set of test data for use in integration tests, and create integration tests which operate on the real database and schema to test these queries.  Data does not need to be exhaustive, it needs to check each operational process.

These integration tests will be using the jormungandr API, and so can not be fully tested until it is.

### Subtasks
 - [ ] Setup the test database data.
 - [ ] Create an endpoint and load tester from a fork of the catalyst load tester.
   - [ ] Can a vote be added to the DB correctly?
   - [ ] If a vote for the same voter on the same proposal is case, is it rejected and not accepted by the DB?
   - [ ] Given several votes cast for several voters, can the query reliably return the votes cast for a individual voter.
   - [ ] Can the query reliably return all votes cast in chronological order.
   - [ ] External API tests across all these endpoints that proves they work correctly, in concert.

 This will enable us to not only validate the endpoints behave as required but also to test them under both high volumes and determine the performance characteristics under load.

We fork the load tester so that we can make it more appropriate for testing catalyst voices without worrying about production stack compatibility.
