### ISSUE TITLE
🏛️ [EPIC] : Fund14 Testing Readiness

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#1253]
### Summary

Ideascale replacement and integrations with legacy stack

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Intent

Deliver the core proposal submission and commenting functionality in the new Catalyst UX to replace Ideascale. Integrate the new backend and application with legacy components (eg Reviews module, scripting, mobile voting app). Be ready for end to end testing of the Fund14 production stack by mid February. 

### Description

**New Stack**
- ADMINS will coordinate with QA and SRE to hardcode all operating parameters (with no treasury space / campaign builder UI).
- ALL USERS will submit role0 registrations to mainnet (with role specific contributions tracked by the backend to retroactively associate with role keys in the future). 
- PROPOSERS will create, edit, share (discovery), and submit (voting) proposals
- COMMENTERS will browse proposals by category in the discovery space (drafts), and provide feedback through proposal-level comments

**Legacy Stack**

- ADMINS will make sure that all legacy scripting and tools (prev cat-core/catalyst-toolbox) works with the intermediate stack intended for production in Fund14; also make plans to automate the most costly operations, prioritize them, and map features to the new stack
- REVIEWERS will use the standalone reviews/moderation module to review proposals from Voices
- VOTERS will use the legacy voting app to search, sort, and filter, and vote on proposals from Voices that include review/moderation data from the standalone reviews/moderation module
- FUNDED PROJECTS will have their proposal and milestone details from Voices pre-loaded in the standalone milestone module

### Outcome 

As a user, I get a fit-for-purpose proposal editing and feedback experience, so that I can do my best work in Catalyst.    

As an operator, I get to fire Ideascale, so that I can lower costs, reduce friction, and remove external blockers to continuous improvement. 

As an ecosystem, we want to improve the quality of proposals and deliberation, so that we can maximize the impact of funds allocated. 

### Design
- [ ] Workspace / index page + label published for f14 + banner download voting app and vote between x-y
- [ ] Extract relational content
- [ ] Inform important deadlines (we show campaign dates list - vit-ss)
- [ ] Category select (action) - modal - select - add in a extra segment. (Hard code data)
- [ ] (New actionbar)Publish for Voting + label in index page.
- [ ] Voting result in projectcatalyst.io
- [ ] Results in Voices as embed results subpage? link to PC.io
- [ ] What pages would we embed? Result for fund X not yet avaiable, Show show results.
- [ ] Bring mobile data into discovery space. DISPLAY ONLY. STATIC RESULTS
- [ ] Communication should focus on projectcatalyst.io Results
- [ ] Don't show  Voting Space.
- [ ] Comments pattern, inline, 1 level deep for discovery and workshop
- [ ] ONE ROLE REGISTER
- [ ] GREY OUT VOTER / DREP.
- [ ] Discovery Browse, Search, Filter with vit-ss data ?? - Same API other path for interim F14 version.
- [ ] //Side quest: revisit role names and descriptions pre-production

### Architecture 
- [ ] Brands, campaigns, categories, proposals, comments, reviews, votes ecosystem data architecture - transition state, MVP state, decentralized state
- [ ] RBAC strategy by Fund for 2025

### Operations
- [ ] Transition plan - integrate old voting app with new voting stack (no propose)
- [ ] Rebuild ideascale reviews process into moderation module
- [ ] Reviews / moderation module get proposal data from voices backend
- [ ] Reviews / moderation module API for voices to get moderated reviews data [F15 enabler]
- [ ] Milestone module get proposal data from voices backend

### Backend 
- [ ] crud proposals
- [ ] get proposal editor/template
- [ ] ideascale simulator (python script -> vit ss) for prod mobile app
- [ ] rbac endpoint
- [ ] cip36 endpoint
- [ ] extra: crud comments

### Frontend
- [ ] f13 template as is (json)
- [ ] proposal(s) (from json)
- [ ] crud proposal for proposer (backend)
- [ ] pull results from vit-ss (asap)
- [ ] rbac endpoint integration
- [ ] extra: comments

### QA
- [ ] Test backend
- [ ] Test frontend
- [ ] F14 end to end testing

### SRE
- [ ] deploy cat-gateway
- [ ] connect  frontend and backend
