### ISSUE TITLE
🏛️ [EPIC] : Design Tasks for Fund14 Readiness

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#1254]
### Summary

Fund14 Readiness Design

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

Child of https://github.com/input-output-hk/catalyst-voices/issues/1253

- [ ] Workspace / index page + label published for f14 + banner download voting app and vote between x-y
- [ ] Extract relational content
- [ ] Inform important deadlines (we show campaign dates list - vit-ss)
- [ ] Category select (action) - modal - select - add in a extra segment. (Hard code data)
- [ ] (New actionbar)Publish for Voting + label in index page.
- [ ] Voting result in projectcatalyst.io
- [ ] Results in Voices as embed results subpage? link to PC.io
- [ ] What pages would we embed? Result for fund X not yet avaiable, Show show results.
- [ ] Bring mobile data into discovery space. DISPLAY ONLY. STATIC RESULTS
- [ ] Communication should focus on projectcatalyst.io Results
- [ ] Don't show  Voting Space.
- [ ] Comments pattern, inline, 1 level deep for discovery and workshop
- [ ] ONE ROLE REGISTER
- [ ] GREY OUT VOTER / DREP.
- [ ] Discovery Browse, Search, Filter with vit-ss data ?? - Same API other path for interim F14 version.
- [ ] //Side quest: revisit role names and descriptions pre-production
- [ ] Revisit account creation and role registration; adapt to limited scope of initial implementation eg remove role selection

### <list 1 name>

- [ ] #1
- [ ] #2
- [ ] issue description when not yet created.

### <list 2 name>

- [ ] <issue>
- [ ] <issue>
- [ ] <issue>
