### ISSUE TITLE
🏛️ [EPIC] : Frontend Tasks for Fund14 Readiness

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#1255]
### Summary

Fund14 Readiness Frontend

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

Child of #1253 

- [ ] f13 template as is (json)
- [ ] proposal(s) (from json)
- [ ] crud proposal for proposer (backend)
- [ ] pull results from vit-ss (asap)
- [ ] rbac endpoint integration
- [ ] extra: comments

### <list 1 name>

- [ ] #1
- [ ] #2
- [ ] issue description when not yet created.

### <list 2 name>

- [ ] <issue>
- [ ] <issue>
- [ ] <issue>
