### ISSUE TITLE
🏛️ [EPIC] : RBAC Design

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#128]
### Summary

Design RBAC (Role-based access control) standards for Catalyst Voices

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-8552

### Description

This is to deliver on Part 1 and 2 of Milestone 2 of the Catalyst Voices Proposal Milestones.

### Define on-chain registration standard for RBAC

- [ ] #210
  - [ ] Voters
  - [ ] Representatives
  - [ ] Voters Delegating to Representatives
  - [ ] Proposers
  - [ ] Co-Proposers
  - [ ] Reviewers
  - [ ] Flexibility to encompass other roles
  - [ ] Ensure cross dapp usability.
- [ ] Prepare documentation updates
- [ ] Create reference implementation
- [ ] Create test vectors of registration formats.
- [ ] Publish and seek community feedback
  - [ ] Incorporate feedback into documentation and standards
- [ ] Submit as a CIP and follow through the standardization process.

### Define CIP-30 extensions to fulfill capabilities needed of the registration formats and dapps.

- [ ] Update or replace CIP-62 to:
  - [ ] Enhance Voter registration to be able to properly process the changes defined in the CIP-36 draft. (This is necessary to support permissionless authorization and to ensure data submitted is authoritative.)
  - [ ] Facilitate the ability to sign data securely with both Software and hardware.
  - [ ] Enhance Vote Signing to use the correct keys for Representatives or Voters.
- [ ] Prepare the CIP-36 Documentation Updates
- [ ] Produce a Mock Development Wallet which provides a reference  implementation of the Changes introduced in this update.
- [ ] Publish and seek community feedback and input on changes proposed.
  - [ ] Incorporate necessary changes based on feedback.
- [ ] Submit changes upstream to the CIP editors for review and inclusion as an official CIP.
- [ ] Includes the work entailed to steward the CIP update through the CIP Process.

### Snapshot Tooling enhancements:
- [ ] Capture the different roles defined by catalyst.
- [ ] Calculate Voting Power or other Role specific requirements at snapshot time.
- [ ] Properly handle multiple snapshot deadlines for different roles.
- [ ] Import the role registrations on a periodic basis into the Catalyst Backend Database.

### CIP Process Tracking

The following PR's to formalize CPS/CIPs arising from this Milestone are listed here.
Tracking of thes PR's may need to move to new Milestones if they are not fully merged before the Milestone is complete.

- [x] https://github.com/input-output-hk/catalyst-CIPs/issues/4
- [ ] https://github.com/input-output-hk/catalyst-CIPs/issues/5
- [x] https://github.com/cardano-foundation/CIPs/pull/751
- [x] https://github.com/cardano-foundation/CIPs/pull/752
- [x] https://github.com/cardano-foundation/CIPs/pull/753

### Prototyping and Tooling

- [x] #299
