### ISSUE TITLE
Additional F14 modules for input / data capture

### ISSUE THREAD

**Issue by nielskijf** [input-output-hk/catalyst-voices#1285]
New epic #1410 

# TODO
Sync naming convention
 https://github.com/input-output-hk/catalyst-voices/blob/feat/proposal-template-drafting/docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json

### Workthrough
- [ ] Design discovery on input/data capturing done [here](https://www.figma.com/design/1e1MMDXyi0oL9sG9IunWL7/UI-Kit-Figma-for-catalyst?node-id=2756-31103&t=My25qY5GsIajqP7e-4). This will be simplified for F14!
- [x] Brought in category F13-F14 Cardano Open: Developers (Only open source cat!, see below.)
- [ ] Link F12 category questions - [link](https://docs.google.com/spreadsheets/d/1aRSRKksiFHRVGT9B7kqOFjbolcXX-m1vAgAmMlKXtFU/edit?gid=0#gid=0) - needs consolidation with F13
- [ ] Extract questions from other cats (todo)

### Capture module list here: 
- [ ] Q & A (simple text)
- [ ] Q & A (rich text) - limit rich-text more for F14 (ask nathan)
- [ ] Upload document
Rich text:
"bold", "italic", "underline", "link", "bulletList", "numberedList"
 Supported docs
".pdf", ".doc", ".docx"
- [ ] Simple conditional y/n - answer + validation
- [ ] budget related input / number input, + min/max ranges
- [ ] Conditional question, bring into validation? Y/N Input + validations (https, url, one line, simple text)
- [ ] Checkbox + url input validation (depends on ask / Https validation?) - Offer multi need be.
- [ ] Radio-button (select one)
- [ ] Dropdown/selection solution (select one)
- [ ] Ownership select ? co-ownership select? (How does this work we don't have memberlists?) @mike-mcnulty 
- [ ] Conditional CAT/TAG selection? Select multiple? See onboarding / Twitter/X onboarding.
---
### Requirements
- [ ] Category is added in through the action bar (bottom rail)
- [ ] Category is added to the let-rail menu (inserted after category selection (modal), perhaps top segment?)
- [ ] Category can be changed, would be awesome if the user could switch back to previous category selection in edit view.
- [ ] Earlier selected categories / filled out categories, keep data.
- [ ] No category selected blocks publishing ability.
- [ ] Seems category questions are unique, making transfer of data between category not needed. @mike-mcnulty 

### Additional Category Questions segment/section for Cardano Open: Developers  
- [ ] This is the only open source category, so we can remove the open source questions from the base proposal template.
- [ ] Q: Is your project open source? y/n 
Condition No:
- [ ] Sorry your project is not egible for funding? What happens (export?)
---
Condition Yes:
- [ ] Q: Please provide a description of your open source project:
- [ ] Q: text-area, charmax 300.
- [ ] Q: What open source license do you use?
- [ ] A: Dropdown with open source licenses?
- [ ] Internal: Is there a list of licenses available? @mike-mcnulty 
- [ ] Q: Provide url for project repo
- [ ] A: input url  | https validation
- [ ] Q: Provide url for project documentation
- [ ] A: Input url  | https validation
- [ ] Q: Provide 3-5 keywords for your tooling|
- [ ] A: Input separate by comma , turn into chip
---
- [ ] Q: You acknowledge the category eligibility criteria | y/n  
Condition No: 
You need to accept the category eligibility criteria to be able to publish your proposal for funding.
Condition Yes:
After saving your category and provided information, your category mandatory tasks is cleared in the actionbar.
link: check now.
---

Attention, not for F14:
- [ ] Milestone & Cost breakdown module might be a enormous win? @mike-mcnulty

**Comment by mike-mcnulty** [comment]
Completed as part of F14 design handoff
