### ISSUE TITLE
🏛️ [EPIC] : F14/F15 Operations Dependencies

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#1332]
### Summary

Operations Dependencies

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

The internal operations team requires features in the new platform in order to deliver continuity of service to existing contributors and grantees. 

More ad hoc and manual processes will be required to satisfy these requests in Fund14, with higher priority being placed on the core proposal submission and commenting required to replace Ideascale as the primary proposer interface. 

In Fund15, an admin role will be introduced in the new platform, along with greater configuration and management capabilities not prioritized for the initial launch in Fund14. 

### Fund14: Proposal Submission & Commenting (Discovery Space + Workspace Only)

**User Management**
- [ ] 🛠️ [TASK] : Associate historical user IDs with new user accounts [1.1]
- [ ] 🛠️ [TASK] : Redirect funded proposers to project onboarding [1.2]
- [ ] 🛠️ [TASK] : Document manual process to remove non-compliant content [1.3, 1.4]
- [ ] 🛠️ [TASK] : Allow email opt-in for mass communications [1.5]
- [ ] 🛠️ [TASK] : Leave public comments as an admin for custom communications [1.5]
- [ ] 🛠️ [TASK] : Integrate zendesk ticket creation with user context [1.6]

** User Registration**
 - [ ] 🛠️ [TASK] : Accept privacy policy and T&C during registration [2.1]

**Proposal Moderation**
- [ ] 🛠️ [TASK] : Document manual process to update proposal category [3.1]
- [ ] 🛠️ [TASK] : Document manual process to update proposal status (draft / published) [3.2, 3.3]

**Data Export**
- [ ] 🛠️ [TASK] : Get campaign data from API [4.1]
- [ ] 🛠️ [TASK] : Get proposer data from API [4.2] 

**Commenting**
- [ ] 🛠️ [TASK] : Comment on draft proposal in discovery space as a registered user [5.1]
- [ ] 🛠️ [TASK] : View proposal comments in workspace as a proposer [5.1]
- [ ] 🛠️ [TASK] : Edit / delete comment [5.1, 5.2]
- [ ] 🛠️ [TASK] : Research how to notify proposer if proposal metadata updated by admin [5.2]

### Fund15: Campaign Builder, Voting, & Liquid Democracy (Treasury Space, Voting Space, Delegation / Dreps)

**User Management**
- [ ] 🛠️ [TASK] : Remove non-compliant content as an admin [1.3, 1.4, 5.2]
- [ ] 🛠️ [TASK] : Research spike on P2P Chat [1.5, 5.2]
- [ ] 🛠️ [TASK] : Research spike on notifications [1.5, 5.1, 5.2]
- [ ] 🛠️ [TASK] : Research spike on web3-native email replacement [1.5, 5.2]

** User Registration**
- [ ] 🛠️ [TASK] : Research spike on KYC credential for Catalyst keychain [2.1]

**Proposal Moderation**
- [ ] 🛠️ [TASK] : Update proposal category as an admin [3.1]
- [ ] 🛠️ [TASK] : Update proposal status (draft / published) as an admin [3.2, 3.3].

### <list 1 name>

- [ ] #1
- [ ] #2
- [ ] issue description when not yet created.

### <list 2 name>

- [ ] <issue>
- [ ] <issue>
- [ ] <issue>
