### ISSUE TITLE
🛠️ [TASK] : Dynamic frontend config

### ISSUE THREAD

**Issue by damian-molinski** [input-output-hk/catalyst-voices#1348]
### Summary

Frontend config should be dynamic base on config from backend

### Background
Backend already has `GET api/draft/config/frontend` ([link](https://input-output-hk.github.io/catalyst-voices/api/cat-gateway/openapi/)) which should be extended with additional object.

```json
{
   "sentry":{
      "dsn":"https://example.com",
      "environment":"dev",
      "release":"1.0.0"
   },
   "cache":{
      "expiry_duration":{
         "keychain_unlock":10000
      }
   }
}
``` 

any field inside `expiry_duration` should be in seconds.

All of fields are nullable so frontend have to assume default values. App should still work without calling endpoints, just with fallback config.

### Tasks:

- [ ] Extend `GET config/frontend` endpoint with `cache` objecy
- [ ] Caching with configurable duration from global object.
- [ ] Consume dynamic config endpoint
