### ISSUE TITLE
🏛️ [EPIC] : Catalyst Voting Power and Registration capture

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#141]
### Summary

Add functions to capture voting power and registrations in support of RBAC requirements

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-8577

### Description

This Epic tracks the work to capture Voting power information and registration data in Catalyst Voices.

### Voting Power (Native ADA)
- [x] [ Initial low level design for catalyst gateway / follower mechanics.](https://github.com/input-output-hk/catalyst-voices/issues/205)
- [x] [ Gateway follower boostrap](https://github.com/input-output-hk/catalyst-voices/issues/217) with initial blockchain indexing.
- [x] Index transactions and[ utxo data.](https://github.com/input-output-hk/catalyst-voices/issues/250)
- [x] [Obtain stake credential from TX payloads](https://github.com/input-output-hk/catalyst-voices/issues/302)

- [x] [Mithril snapshot](https://github.com/input-output-hk/catalyst-voices/issues/262) benchmarks

- [x] Capture latest UTXO Data from Cardano live from the chain (internal task of catalyst voices)
    - [x] DB Query to insert a block of UTXO data into database (replacing any obsoleted data).
- [x] Capture latest Spent TXO Data from Cardano live from the chain (internal task of catalyst voices)
    - [x] DB Query to insert a block of Spent TXO data into database (replacing any obsoleted data).
- [x] Create DB query to read all UTXO data into memory from DB (Or a time banded portion of UTXO data).
- [x] Create DB query to read all Spent TXO data into memory from DB (Or a time banded portion of UTXO data).
- [x] Create a function to calculate for a given stake address, at a given time, the total UTXO associated with that address at that time (from the in-memory data) #309.
- [x] https://github.com/input-output-hk/catalyst-voices/issues/378
- [x] https://github.com/input-output-hk/catalyst-voices/issues/395

### Registration Data

- [x] [ Capture and parse latest CIP15/36 Registration data on a periodic basis (internal task of catalyst voices)](https://github.com/input-output-hk/catalyst-voices/issues/300)
    - [x] DB Query to insert a block of CIP15/36 registration data into database (replacing any obsoleted data).
    - [x] #293
- [x] Create DB query to read all Valid CIP 15/36 registration data into memory from DB.
- [x] Create DB query to read all invalid CIP 15/36 registrations for a stake address from DB.

**Comment by minikin** [comment]
Done.
