### ISSUE TITLE
🏛️ [EPIC] : TODO comments

### ISSUE THREAD

**Issue by bkioshn** [input-output-hk/catalyst-voices#237]
### Summary

TODO comments

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-8987

### Description

As our codebase grows, it's essential to ensure that all TODO comments existing within our codebase are properly managed to maintain consistency and fix all potential issues.

#### 🎒Catalyst Voices Backend
- [ ] https://github.com/input-output-hk/catalyst-voices/issues/238
- [ ] https://github.com/input-output-hk/catalyst-voices/issues/239

#### 🕸️ CI/CD

- [ ] https://github.com/input-output-hk/catalyst-ci/issues/188
