### ISSUE TITLE
🛠️ [TASK] : Recheck validation value

### ISSUE THREAD

**Issue by bkioshn** [input-output-hk/catalyst-voices#239]
### Summary

Recheck validation value

### Description

Some Poem `validator` value are set just to make the auto-generated OpenAPI specification pass the OpenAPI linter.

## Task
- [x] Recheck the `max_items` for `Vec`
- [x] Recheck the `max_length` for `String`
- [x] Recheck the `maximum` for number
- [x] Recheck the `pattern` for `String`

**Comment by apskhem** [comment]
Resolved in this [PR](https://github.com/input-output-hk/catalyst-voices/pull/1787)
