### ISSUE TITLE
🏛️ [EPIC] : Milestone 2 Wrapup

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#290]
### Summary

Deliver Milestone 2 to the community

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-9098

### Description

At each Milestone, we will publish tagged versions of the code base and a test report showing that all the proposed features are correctly built and have been delivered and tested. We will also prepare recorded demonstrations of the completed functionality, as appropriate.

Sessions will be conducted during the development process to discuss the work completed and ongoing and give the community access to not only check for themselves the work being delivered but to question the development team about the project to allow a better understanding of the system to be fostered between the developers and the community.

### Todo

- [x] Apache-2 Licenses applied correctly to all code and no license conflicts in any dependent libraries.
- [x] Repository tagged as at Milestone completion.
- [x] Test report covering delivered functionality.
    *  https://github.com/input-output-hk/catalyst-voices/actions/runs/8663170363
- [x] RBAC Documentation published.
    * https://input-output-hk.github.io/catalyst-voices/catalyst-standards/draft-cips/
    * https://github.com/input-output-hk/catalyst-voices/tree/main/docs/src/catalyst-standards/draft-cips
- [ ] Public online session and demonstration covering work completed, and allow community feedback within the forum.

### Milestone Reviewer Feedback

- [x] https://github.com/input-output-hk/catalyst-core/issues/695
- [x] Create loom addressing concerns around "deploy minimally functional UI to testnet", discuss with reviewers, and take further action as required
- [x] Align with CIP editors on best practices for progressing draft CIP, decide on next steps, share & discuss with reviewers, and take further action as required
- [x] Resolve any outstanding access issues with PoA materials (eg videos)

**Comment by mike-mcnulty** [comment]
Milestone 2 approved and signed off in milestone module
