### ISSUE TITLE
[EPIC] Notifications & Announcements

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#321]
The Catalyst Voices platform will use notifications to keep users informed of important information such as: recent activity, pending tasks, and event announcements.

Users will be able to set their notification preferences based on their role, as well as events they would like to participate in. Users need to be able to see new notifications, and review the history of notifications in a persistent location. 

Admin users will be able to set notifications for an event, configure them to send to specific user types, and schedule them for automatic sending.

*Though they may share a similar location in the app, we may distinguish between "Notifications" and "Announcements"; where Notifications refer to activity and reminders that are specific to an individual user, while Announcements are messages sent by admins to all users of a certain type. 

**All items in epic need further discussion to refine understanding of users needs, and to align on MVP vs post MVP scope. Note that neither notifications nor announcements appears in the commitments made in the F10 proposal, and careful attention should be paid to scope creep in evaluating features for inclusion in the MVP. 

User Needs

- [ ] View new notifications
- [ ] View history of notifications
- [ ] Voters notified about registration & voting deadlines, plus voting result announcements, and rewards calculation & distribution
- [ ] Dreps notified about registration & voting deadlines, plus voting result announcements, plus new (un)delegations & saturation warnings, and rewards calculation & distribution
- [ ] Delegators notified about delegation deadline, drep inactive or saturation warning, voting result announcements, and rewards calculation & distribution
- [ ] Proposers notified about submission deadlines, community comments, voting windows, voting activity and result announcements
- [ ] Team members notified about new proposal activity, team comments, submission deadlines, and team tasks
- [ ] Users that leave comments notified about replies to comments
- [ ] Users that subscribe to an Event or Proposal notified about new activity and updates
- [ ] Ability to mark notifications as read / unread
- [ ] Ability to permanently delete notifications

Admin  Needs

- [ ] Ability to create and send ad hoc messages to all users of a certain type
- [ ] Ability to define announcements during the Campaign Setup
- [ ] Ability to write a short paragraph that will be sent to users
- [ ] Ability to define user segmentation for receiving notification (eg by role)
- [ ] Include links in the notification - either deep link in app or external link
- [ ] Schedule announcements - either by date, or in relation to a timeline milestone
- [ ] View analytics on announcements (eg Sent vs Viewed vs Click-Throughs)

**Comment by mike-mcnulty** [comment]
TODO: consider this together with task / inventory management
