### ISSUE TITLE
🏛️ [EPIC] : Catalyst Gateway Voting

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#35]
### Summary

First phase of an improved vote storage solution for catalyst voices

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-8295

### Description

Vote storage solution for Catalyst Voices.

The Catalyst gateway will become an improved vote storage mechanism for Catalyst and the staging ground for work on fully decentralizing vote storage which will only be fully realized in the Hermes/Athena projects.

### Phase 1 - API Setup

In this phase, API endpoints will be created, with no functionality, that answer the same API calls as the existing jormungandr node.
These APIs are interim and allow us to have backwards compatibility, so even though we are implementing them new, they are to be marked as `deprecated` to signal our intent to obsolete them.

This Phase does not create any implementation beyond setting up the endpoints themselves, and setting up the data structures associated with the requests and responses.  The OpenAPI documentation must be fully complete for each endpoint to be Done.

We ONLY need to implement endpoints that are used by:
1. The Mobile voting app
2. The Web based voting app GVC (Which can be assumed to be identical to the Mobile voting app for this process).
3. Produce results from tally, or are involved in the tally.
4. Other endpoints inside jormungandr are NOT to be implemented.
5. The behavior of any and all CLI tools regarding these APIs is out of scope and backward compatibility with them is also out of scope.  No work will be done to support backwards compatibility with CLI tools, either for Voting or operational purposes.

Even if an endpoint is listed in these tasks, it must be validated if it fits the above criteria before work commenced.
Any endpoints that fit the above criteria, but are not listed, needs to be raised with engineering management BEFORE being added to the list.
Any endpoint to do with the operation of voting, such as fragment logs are out of scope and that data will be reported by alternative means.
Endpoints also only need to be implemented as far as the response is used by an in-scope application.  This needs to be validated.
For example, if an endpoint return 35 fields, but the app only uses 2 of them and ignores the rest, then response needs to be reduced to the set of data the app needs to operate correctly and all other data excluded.

Do not rely solely on the existing API documentation validate against both:
1. Jormungandr code
2. Norns voting app

- [ ] /api/v0/vote/active/plans
- [ ] /api/v0/message <- ONLY if its used by a current app in production to post votes.
- [ ] /api/v1/fragments
- [ ] /api/v1/fragments/statuses
- [ ] /api/v1/votes/plan/account-votes/{account_id}

### Phase 2 - DB Setup

Votes will be stored into the postgres db, pending archival into an indelible voting ledger.
All valid votes logged to the DB will be assumed to be also in the voting ledger for this phase.

- [ ] Design a DB table schema which is sufficient to store unique votes per proposal, per challenge, per registered voter, per fund.
- [ ] Add a query to the event-db crate which tries to store a vote and fails if a vote is already stored (can not overwrite votes).  This failure is a normal operational occurrence, and so must inform the caller the voter has already voted.  Its not an ERROR per-se.
- [ ] Add a query to the event-db crate to return cast votes for a voter for a fund,  and optionally, for a challenge, or even a check if they voted on a particular proposal.
- [ ] Ensure the schema has appropriate indexes to make both of these quries efficient.
