### ISSUE TITLE
🛠️ [TASK] : Campaign Builder / Proposal Builder

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#354]
### Summary

Design mini form builder for proposals

### Description

As an admin, I need to be able to define proposal questions with a simple form builder, so that I can quickly update and deploy proposal templates without requiring coordination with development.

Proposal template management will take place from inside the campaign builder. Users will launch the form builder from inside the Proposal Setup section of the campaign builder. While inside the form builder, users will get contextual navigation bar and just-in-time assistance, similar to the Proposal Workspace. 

Each field to be defined by...
- Field Name
- Field Description
- User Input Type
- Input Validations

Each User Input Type will correspond to a particular component in the UI kit that defines how field should be rendered in the application (eg font, text size, padding). This should be selected by the admin user from a dropdown.

Types to include...
- Text
- Number
- Checkbox
- TextArea
- Select
- Multiselect

Input validations will control what users can / cannot enter into a particular field. This should be configurable by the admin user, based on the input type selected.

Validations to include...
- Character limit for text
- Min / max for number
- Required field for any field type
- Is link / Is email for text
- Arbitrary regex for text OR number

All validations will be performed on the flutter application side, in order to reduce development effort, while maintaining an excellent user experience. If any user inputs violate a validation rule, then the application should notify users and provide guidance to resolve in real time. Upon user submission of the form, the application will convert the JSON into binary format to be passed to the backend. 

Out of scope: localization of forms to be rendered in local language of the user.

### Tasks

- [ ] DESIGN overall form builder UX
- [ ] DESIGN form builder UX in context (ie modal, connection to campaign builder)
- [ ] DESIGN form builder error handling
- [ ] DEVELOP manage sections
- [ ] #366 
- [ ] #367 
- [ ] #368 
- [ ] #369 
- [ ] DEVELOP form builder in flutter
