### ISSUE TITLE
🏛️ [EPIC] : c509 library for use in rust or js/wasm in a browser

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#386]
### Summary

Create a library to create and process C509 Certificates

### JIRA Epic

TODO

### Description

We need a crate that allows us to create C509 Certificates.
It also needs to be able to read and validate a C509 certificate and needs an interface to return data held within a certificate.

The Crate needs to be usable as a library from Rust,  but also to build to wasm and have Javascript bindings so that it can be used in browser and also from flutter.

We will build on the Draft9 specification unless a later revision is released.

The library will go here: `catalyst-voices/catalyst-gateway/crates`
The library will be called `c509-certificate`

Reference:
* https://datatracker.ietf.org/doc/draft-ietf-cose-cbor-encoded-cert/
* https://github.com/cose-wg/CBOR-certificates (Rough example code, not a library or usable implementation).
* https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_Wasm
* https://rustwasm.github.io/docs/book/introduction.html

### Setup

- [ ] Create the Crate and ensure it can build to webasm and produce necessary javascript bindings. (No actual code, just a placeholder function to get the build right).
- [ ] Add a set of builder functions to allow the easy creation of C509 certificates.
  - [ ] Function to create a CBOR re-encoding of X.509 v3 DER Certificate  (Code linked above can be used as a starting point for this).
  - [ ] Function to go back to a DER certificate from a c509 CBOR re-encoding of X.509 v3 Certificate 
  - [ ] Support creation of Natively Signed C509 Certificate following X.509 v3 
- [ ] Define list of supported cryptography
  - [ ] From the list allow certs to be validated and signed if the necessary keys are presented.

### Related PR
- [x] #389 
- [x] #439
