### ISSUE TITLE
🏛️ [EPIC] : Catalyst RBAC Registration capture and Staking Rewards capture

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#402]
### Summary

Capture and record RBAC registrations and Staking Rewards

### JIRA Epic

TODO

### Description

This ticket extends catalyst voices registration capture to capture:

* Staking rewards both claimed and unclaimed
* RBAC registrations

### ToDo

- [x] #800
- [x] Create query to find rbac registrations given a stake address, or key id.
- [x] Create endpoint to return RBAC registrations for a stake address.
- [x] Capture RBAC metadata from chain 
  - [x] https://github.com/input-output-hk/hermes/issues/324

### Won't Do

- XX Capture Unclaimed staking reward data from Cardano live from the chain (internal task of catalyst voices)
    - XX DB Query to insert a block of unclaimed staking rewards data into database (replacing any obsoleted data).
  Neither of these capabilities are available in Cardano without re-implementing the Ledger Rules._

- XX Capture Claimed staking reward data from dbSync live from the chain (internal task of catalyst voices)
    - XX DB Query to insert a block of claimed staking rewards data into database (replacing any obsoleted data).
   Neither of these are required if capturing staking rewards is not possible.

- XX Create DB query to read all unclaimed staking reward data into memory (Or a time banded portion of UTXO data).
- XX Create DB query to read all claimed staking reward data into memory (Or a time banded portion of UTXO data).
  Neither of these can be done without the staking reward  data, which can not be captured.
