### ISSUE TITLE
🏛️ [EPIC] : Develop general interface components

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#475]
### Summary

Develop general interface components

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

This epic is aimed at developing the flutter / dart UI kit and components required to implement the general interface components described in #105. 

### Layouts
- https://github.com/input-output-hk/catalyst-voices/issues/488

### Spaces Menu
#379 
- [x] Brand navigation
   - [x] Logo, Name
   - [x] Search
- [x] [Space] Menu
   - [x] Primary Menu Item
   - [x] Secondary Menu Item
   - [x] Selected Menu Item
   - [x] Add Item (“+”)
   - [x] Item Details (“...”)
   - [x] Status Pill

### Header

- https://github.com/input-output-hk/catalyst-voices/issues/491
  - https://github.com/input-output-hk/catalyst-voices/issues/496
  - https://github.com/input-output-hk/catalyst-voices/issues/497

#380 
- [x] Branding (Logo, Name)
- [x] Main Menu
- [x] Hamburger Menu
- [x] Spaces Pill
- [x] Spaces Dropdown
- [x] Logged Out State
- [x] Sign In Button
- [x] Get Started Button
- [x] Logged In State
- [x] Call to Action Button
- [x] Settings Icon
- [x] Settings Menu
- [x] Profile Icon
- [x] Profile Menu

### Contextual Navigation
- https://github.com/input-output-hk/catalyst-voices/issues/539
- https://github.com/input-output-hk/catalyst-voices/issues/567

#381 
- [x] Title
- [x] Open / Close Navigation Panel
- [x] Segment Name
- [x] Expand / Collapse Segment
- [x] Section Name
- [x] Show / Hide Section
- [x] Selected Section

### Assistant
#382 
- [ ] Title
- [ ] Open / Close Assistant Panel
- [ ] Section
- [ ] Current Section
- [ ] Content Card Title
- [ ] Content Card Details
- [ ] Content Card Author
- [ ] Content Card Action

### Toolbox
#383 
- [ ] Title
- [ ] Open / Close Toolbox Panel
- [ ] Toolbox Tabs
- [ ] Column Headers
- [ ] Item Title
- [ ] Item Details
- [ ] Item Status Pill
- [ ] Item Action 
- [ ] Item Action Menu
- [ ] Toolbox summary details
- [ ] Toolbox take action

**Comment by mike-mcnulty** [comment]
completed with mve1
