### ISSUE TITLE
🛠️ [TASK] : Configure dart license checker to prevent use of not compatible packages

### ISSUE THREAD

**Issue by dtscalac** [input-output-hk/catalyst-voices#485]
### Summary

Configure dart license checker to prevent use of packages with incompatible licenses.

### Description

The goal of the task is to prevent usage of dart/flutter packages that are sourced under incompatible licenses. This can be achieved by using 3rd party tools that scan pubspec.lock files where all direct and indirect (transitive) dependencies are listed, analyzing their licenses and rejecting the incompatible ones.

### Todos
- [x] Get familiar with analyzer tools: [license_checker](https://pub.dev/packages/license_checker), [dart_license_checker](https://pub.dev/packages/dart_license_checker).
- [x] Configure a preferred license checker for catalyst_voices package, allowed licenses: MIT, Apache-2.0.
- [x] Report any packages that are using unauthorized licenses, wait for a team decision and either allow these licenses or remove these dependencies.
- [x] Create an earthly check target that runs on CI that prevents packages with unauthorized licenses.
- [x] Find a way to reapply the licenses checker for all dart/flutter packages minimizing the configuration boilerplate. The configuration will be the same for all of the packages.
