### ISSUE TITLE
🏛️ [EPIC] : Enhance backend to support new roles

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#503]
### Summary

Enhance backend to support new roles

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

Need to update the catalyst backend database to support new role registrations. 

### Todo

- [ ] Capturing all defined roles.
- [ ] Recording Earned Rewards and Payment information for each registration.
- [ ] Define Parameters for each registrations snapshot and deadline.
   -Allows each role to have a different set of minimum requirements.
   -Allows the deadline for different roles to occur at different times relative to the Fund Cycle.
