### ISSUE TITLE
🏛️ [EPIC] : Update cat-data-service to fix chain sync issues

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#504]
### Summary

Update cat-data-service to support new role registrations

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

Need to update cat-data-service to support new role registrations

### Todo

- [x] #528
- [x] #529
  - [x] Make sure that indexing can be restarted efficiently if it stops.
- [x] #691
- [x] Incorporate the new CIP-36/Staked Token data into existing or new endpoints. 
  - [x] #690 
  - [x] #850
- [x] Provide endpoints to return any detected errors with CIP-36 Role Registrations, and a users registration history.
  - [x] #687
  - [x] #849 
- [x] #887
- [x] https://github.com/input-output-hk/hermes/issues/338
- [x] https://github.com/input-output-hk/hermes/issues/336
- [x] https://github.com/input-output-hk/hermes/issues/333
- [x] https://github.com/input-output-hk/hermes/issues/328
- [x] https://github.com/input-output-hk/hermes/issues/326
- [x] https://github.com/input-output-hk/hermes/issues/300
