### ISSUE TITLE
🏛️ [EPIC] : Local and CI Deployment Testing via K8s test cluster

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#525]
### Summary

Use a local K8s cluster for both Local development and CI Integration tests

### JIRA Epic

TODO

### Description

Change from using Docker-in-Docker to using a Temporary self deployed K8s cluster.
This cluster can also be used for debugging and development efforts locally.

### Cluster Setup

- [ ] Build the basic local development cluster infrastructure and setup
- [ ] Setup the Catalyst Vocies docs to be deployed to the dev cluster, under an appropriate path.
- [ ] Convert the Docker-In-Docker tests for catalyst-gateway to use the development cluster locally
- [ ] Use the development cluster fully automated in CI for CI integration tests.

### Development Tooling

- [ ] Document how to develop and debug within the local dev cluster
- [ ] Add deployments for the whole Catalyst-Voices stack so that it can run in the development cluster for local testing.
  - [ ] This includes the full Frontend, backend, Database and Mithril snapshots.
