### ISSUE TITLE
🏛️ [EPIC] : Role-base access control implementation

### ISSUE THREAD

**Issue by Mr-Leshiy** [input-output-hk/catalyst-voices#579]
### Summary

Deliverables will include updates to Catalyst Core backend to support role-based registrations and wallet-connect capabilities for the browser-based application.

https://milestones.projectcatalyst.io/projects/1000096/milestones/3

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-10571

### Description

**Backend**
- [x] Blocked by: https://github.com/input-output-hk/catalyst-voices/issues/504
- [x] Capturing Role 0 (Voters Role).
- [x] Recording Payment information for each registration.
- [x] Allows each role to have a different set of minimum requirements.
- [x] Allows the deadline for different roles to occur at different times relative to the Fund Cycle.
- [x] Update the cat-data-service to:
  - [x] Incorporate the new data into existing or new endpoints.
  - [x] Must ensure that role0/voter role registration type can be accurately checked by external tooling.
  - [x] Provide auth middleware to enable permissionless authorization of front end applications for Role 0 registrations.
  - [x] Provide endpoints to return any detected errors with Role Registrations, and a users registration history.
- [x] Documented Public Open API Definition for cat-data-service.
- [x] Automated Test Cases running in CI.

**Frontend**
- [x] Full Support for CIP-30 functions.
- [x] #602
- [ ] RBAC Wallet interface will enable:
  - [x] Registering for a Role, and submitting on-chain.
  - [x] #639
  - [x] Demonstrating dApp/wallet integration to RBAC interfaces to enable permissionless auth to the backend.
    - [x] #675 
- [x] Documented Public API Definition
- [x] Automated Test Cases running in CI
- [x] #791

**Comment by stevenj** [comment]
Relevant CIPS:
https://github.com/cardano-foundation/CIPs/pull/810
https://github.com/cardano-foundation/CIPs/pull/811
https://github.com/cardano-foundation/CIPs/pull/813
https://github.com/cardano-foundation/CIPs/pull/814
