### ISSUE TITLE
🛠️ [TASK] : Design Immutable Storage Ledger which will be used for vote storage and realtime publishing of votes.

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#693]
### Summary

Design Immutable Ledger

#### Outer Data Layer

The ledger is an immutable write once append only tamper proof ledger.
It is to create time banded chunks that reference previous chunks, such that any change to a chunk invalidates all later chunks.

It needs a header block that defines header information about the data in the ledger.
It needs a final block that locks the entire set of chunks and no further chunks can be added.

Data in the header should include:

1. information about the kind of data being recorded. (Think UUID as a definition type).
2. Sub ID 1 - Global ID. (UUID)
3. Sub ID 2 - Local ID. (ULID).
4. Time when it started.
5. Maximum size (time) of each chunk.
6. Creator ID. (Kid x509/c509 certificate).  (128 bit hash of the cert).
7. Data specific CBOR data (specific to the kind of data being recorded).
8. Hash algorithm for chunks. (OID?)  (Blake3).
9. Signature over the hash.

Intermediate Chunks.
1. Marker that says its an intermediate chunk.
2. Chunk index
4. Hash of the previous chunk (copied).
3. Sub ID 2 - Local ID. (ULID).
5. Information explaing a gap in the block production (missing chunks).
6. Data specific CBOR data (specific to the kind of data being recorded).
8. Hash algorithm for chunks. (OID?)  (Blake3).
10. Signature over the hash.

Final chunk
1. Looks like the Intermediate chunk, except its marked final.
2. Has a distinct final data block.

### Tasks

- [x] Make the structure in the Architecture docs for cat voices
- [x] Create Markdown file to explain how the structure works and is to be used.
- [x] Create 1 (or more) CDDL Files to define the structures used in a formal sense.

### References

1. CDDL Spec: <https://www.rfc-editor.org/rfc/rfc8610>
11. Errata to include: <https://www.ietf.org/archive/id/draft-ietf-cbor-update-8610-grammar-01.html>
12. Extensions: <https://www.rfc-editor.org/rfc/rfc9165>
13. Modules: <https://cbor-wg.github.io/cddl-modules/draft-ietf-cbor-cddl-modules.html> and <https://github.com/cabo/cddlc>
