### ISSUE TITLE
🏛️ [EPIC] : MVE1 / Spaces & Navigation

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#726]
### Summary

MVE1

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

As a user, I need empty spaces containers, so that I can navigate across the basic experience & validate interaction patterns. 

Intent: Setup the layered navigation to switch between space, perhaps bring in some animation, and have a clear setup of the specific space menu’s and the overall spaces menu.  All menu’s will be emptied out to start  as simple as possible.

Outcome: Create a basic public facing environment (+pw) to start  building and layering MVE’s. A good feel to navigate between spaces, and perhaps have some shortcuts already to quickly jump around. The menu content and space content is as little as possible, as that's not the intent of this MVE.

Figma [Link](https://www.figma.com/design/80aDAQgoD0v06DO2Sb76ok/Catalyst--Minimal-Valuable-Experiments-(MVE's)?node-id=5131-20654&node-type=CANVAS&t=3Zc0ojlmYef40p8D-0): Catalyst Minimum Valuable Experiments \ MVE1 \ [Space]

### Environments
- [x] #762

### General Interface

- [x] Top navigations
- [x] #734
- [x] #733
- [x] #735
- [x] #740
- [x] #758

### Treasury Space
#719
- [x] Simplified campaign builder
- [x] Treasury space menu

### Discovery Space
#736
- [x] Discovery menu | first use
- [x] Discovery menu | locked
- [x] Discovery menu | unlocked
- [x] Simple content page | first use
- [x] Simple content page | locked
- [x] Simple content page | unlocked
- [x] #757

### Workspace
#737
- [X] Simplified workspace
- [X] Workspace menu
- [x] Workspace modal
- [x] #716
- [x] ~Save text~

### Voting Space
#738
- [x] Simplified voting space
- [x] Voting space menu

### Funded projects space
#739
- [x] Simplified funded projects space

### Overall spaces menu
#715
- [x] overall spaces menu (unlocked only)

### MVE Wrap Up
- [x] #866
- [x] #867
- [x] #872 
- [x] #925
- [x] #938

**Comment by minikin** [comment]
Done
