### ISSUE TITLE
🏛️ [EPIC] : MVE2 / Account Creation

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#727]
### Summary

MVE2

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-7772

### Description

As a user, I need to be able to create an account, so that I can build up my profile and track record over time.

Intent: Strip back account creation to key / role and wallet selection only.

Outcome: Users must be able to create, remove, restore a new account.

Figma: TBD

### General Interface

- [ ] Simple account top nav
- [ ] Get started (create new account)
- [ ] Create account step 1
- [ ] Create account step 2
- [ ] Restore account on device
- [ ] Lock / unlock
- [ ] Remove account from device

### Discovery Space

- [ ] Indication of first use vs locked vs unlocked
