### ISSUE TITLE
🏛️ [EPIC] : Refined RBAC Implementation

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#970]
### Summary

Continued refinement of RBAC implementation

### JIRA Epic

TODO

### Description

Refine the RBAC registration Indexing logic, to capture all necessary roles for Proposers and Delegated Representatives.

### Todo

https://input-output.atlassian.net/browse/NPG-10571

### Description

**Backend**
- [ ] Capturing the Proposer and Delegation roles.
- [ ] Recording Earned Rewards and Payment information for each registration.
- [ ] Define Parameters for each registrations snapshot and deadline.
- [ ] Allows each role to have a different set of minimum requirements.
- [ ] Allows the deadline for different roles to occur at different times relative to the Fund Cycle.
- [ ] Update the cat-data-service to:
  - [ ] Incorporate the new data into existing or new endpoints.
  - [ ] Must ensure that each role registration type can be accurately checked by external tooling.
  - [ ] Provide endpoints to enable permissionless authorization of front end applications for defined role registrations.
  - [ ] Provide endpoints to return any detected errors with Role Registrations, and a users registration history.
- [ ] Documented Public Open API Definition for cat-data-service.
- [x] Automated Test Cases running in CI.
